### PR TITLE
Fix track color change problems and parent problems.

### PR DESCRIPTION
**Pull request by sinnyn**
Track color will get changed between start drawing and finally drawn.
It is because at first the 'label' has no track id. So the color uses its label id. But when drawn, the labels and new track is committed, those labels will have a track id. The color policy uses the track id. So the color changed.

### CODE REVIEW

**Comment by sinnyn** [comment]
@fyu One approach is the commit talking about. It changed the least things and works. But it somehow looks like a trick. Another approach will have track id set at very first time the label is initialized. That will introduce a lot of things. Like makeTrack first and use make* to create labels, and then labels all have a track id set. If to make the second approach easier, then gen* methods should be open to the outside. What's your preference?

**Comment by fyu** [comment]
I think `makeTrack` first in label when it is tracking mode makes more sense. The other labels will be created in the track interpolation or just simple propagation.

**Comment by sinnyn** [comment]
1. Use new label's track as its track id.
2. Prevent newly added empty parent label get selected.
3. New link logic. To link between multiple tracks and single labels.
4. Link test.
5. Revised some old tests with newer style.

**Comment by sinnyn** [comment]
TODO:
Check the delete action on linked labels.
Item selection in track if changes to another item.

**Comment by sinnyn** [comment]
List of bug fixes in this PR
1. Color changed when a box if finally drawn.
2. Revised logic of link two labels.
3. Double click could cause an error.
4. Error when pressing the C key on the center of the ending edge of a polygon.
5. Tracked item will lost it selection status when changed to another item.
6. Attributes and categories will not be kept when draw new label.
7. Track-linking should be Ctrl-l + Enter.
8. Cognito refresh token expired problem.
9. When change a polygon (move or reshape), if jumped to another page not the next page, the move failed.

**Pull request merged**
