### PR TITLE
Supported tracking for polyline.

### PR DESCRIPTION
**Pull request by hxhxhx88**

### CODE REVIEW

**Comment by fyu** [comment]
fixes #450

**Review by cwlroda — APPROVED** [review]
LGTM!

**Comment by hxhxhx88** [comment]
@cwlroda Hi Wei Loon, I found a problem in my unit test and updated the code 😂. Please check the latest commit. Besides, I noticed that some checks are not successful due to issues involving Python, which I guess is relevant to PR #454? If so, I will rebase my code once that PR is merged.

**Comment by cwlroda** [comment]
@hxhxhx88 sorry have been quite busy this week. Which npm version are you using? Seems like the package-lock got modified quite a lot, and I get this message when I try to run `npm run test`:

image

**Comment by hxhxhx88** [comment]
> @hxhxhx88 sorry have been quite busy this week. Which npm version are you using? Seems like `package-lock.json` got modified quite a lot, and I get this message when I try to run `npm run test`:
> 
> image

@cwlroda Looks like you need to run `npm install` before running the test. I introduced a new dependency `jest-expect-message` to help writing unit test in a more readable way:)

**Comment by hxhxhx88** [comment]
> @hxhxhx88 sorry have been quite busy this week. Which npm version are you using? Seems like `package-lock.json` got modified quite a lot, and I get this message when I try to run `npm run test`:
> 
> image
> 
> Regarding PR #454 we are fixing it soon, so I think we can just pull the changes from master once it has been merged

I did not install a particular `npm` manually, but just by running the install script from the code base, as instructed in the README, and worked from scratch on a newly rented bare EC2 machine without any pre-existing dev tools or environment. 

Sorry I haven’t noted that `package-lock.json` was changed so much, but only checked that `package.json` only changed by three lines, as I introduced one new dependency. That’s weird. I’ll look into the issue, meanwhile do let me know if you find something😂

**Comment by hxhxhx88** [comment]
@cwlroda Fixed! It turns out that when initialising the project using the scripts located in the `scripts` folder on Ubuntu, no matter 18.04 or 20.02, an older version of `node` will be installed, namely `node 12.22.12` and `npm  6.14.16`, which uses version 1 of the lock file. After upgrading them to the latest one, i.e. `node 18.3.0` and `npm 8.11.0`, everything will be fine. 
Furthermore, the latest

**Comment by cwlroda** [comment]
> @cwlroda Fixed! It turns out that when initialising the project using the scripts located in the `scripts` folder on Ubuntu, no matter 18.04 or 20.04, an older version of `node` will be installed, namely `node 12.22.12` and `npm 6.14.16`, which uses version 1 of the lock file. After upgrading them to the latest one, i.e. `node 18.3.0` and `npm 8.11.0`, everything will be fine.
> 
> I’m not sure if this will be a concern. If so, our installation scripts might require update.

Ah I see now, the install script installs `node 12.x`. I missed that out while updating the script previously.

https://github.com/scalabel/scalabel/blob/99ab28cf5ef4571e293bd59021c55aadf8f3645a/scripts/setup_ubuntu.sh#L147

@fyu since the current `package-lock.json` is using `v2`, should we drop support for `node 12.x - 14.x` which support `v1`? If the user installs these old versions it may cause backward compatibility issues.

**Comment by fyu** [comment]
> > @cwlroda Fixed! It turns out that when initialising the project using the scripts located in the `scripts` folder on Ubuntu, no matter 18.04 or 20.04, an older version of `node` will be installed, namely `node 12.22.12` and `npm 6.14.16`, which uses version 1 of the lock file. After upgrading them to the latest one, i.e. `node 18.3.0` and `npm 8.11.0`, everything will be fine.
> > I’m not sure if this will be a concern. If so, our installation scripts might require update.
> 
> Ah I see now, the install script installs `node 12.x`. I missed that out while updating the script previously.
> 
> https://github.com/scalabel/scalabel/blob/99ab28cf5ef4571e293bd59021c55aadf8f3645a/scripts/setup_ubuntu.sh#L147
> 
> @fyu since the current `package-lock.json` is using `v2`, should we drop support for `node 12.x - 14.x` which support `v1`? If the user installs these old versions it may cause backward compatibility issues.

It is a good idea to update the install script to the new node LTS version.

**Pull request merged**
