### PR TITLE
Removing sprintf and @types/sprintf dependencies from the package.json

### LINKED ISSUE #187: Replace sprintf with template strings
template strings are much faster than sprintf. A simple benchmark result: https://jsbench.me/3rkcy1xfop

### PR DESCRIPTION
**Pull request by LeonY1**
Fixes #187 

Removing the sprintf and @types/sprintf dependency within the app directory

### CODE REVIEW

**Comment by LeonY1** [comment]
@fyu For the AWS_Config issue I've already added `AWS_SECRET_ACCESS_KEY` and `AWS_ACCESS_KEY_ID` into my secrets within my fork however it doesn't seem to be fixing this issue. Would it have been better to use the csv file for the key access?

**Comment by fyu** [comment]
> @fyu For the AWS_Config issue I've already added `AWS_SECRET_ACCESS_KEY` and `AWS_ACCESS_KEY_ID` into my secrets within my fork however it doesn't seem to be fixing this issue. Would it have been better to use the csv file for the key access?

Those should be all you need. Does the pair work for you in your local environment?

**Comment by LeonY1** [comment]
Would I just add them in my local environment variables?

**Comment by fyu** [comment]
That should work. The documentation for aws configuration is here https://docs.aws.amazon.com/cli/latest/topic/config-vars.html. The goal is to test whether your aws s3 is set up correctly. You probably have logged in the aws console: https://aws.amazon.com/console. You can also check whether you can manually create s3 bucket in the console to make sure the feature is enabled.

**Comment by LeonY1** [comment]
Okay I've gotten it to work locally. I think originally I was blocked by AWS since I was using root keys instead of a service account which creates some sort of separation.

**Comment by LeonY1** [comment]
@fyu Would it better to use dotenv to set up the credentials to maintain setting up the environment variables in an easier fashion?

**Comment by LeonY1** [comment]
Would there be a reason why it works locally but not on Github even with the same `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`?

**Comment by fyu** [comment]
> Would there be a reason why it works locally but not on Github even with the same `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`?

I am not aware of any reason for that. I ran the tests on my machine and they passed. We can merge this PR first, but it is worthwhile to figure out how to run the S3 bucket under your account. I noticed that you didn't turn on github action on your fork. Running github actions on your fork will be a good testing env.

**Pull request merged**
