### PR TITLE
Add selection mode

### PR DESCRIPTION
**Pull request by Scalsol**

### CODE REVIEW

**Comment by Scalsol** [comment]
My solution is: At the beginning, we are in the 'annotating' mode, when we pressing 'z', we will enter 'selecting' mode. In selecting mode, you will be able to select and drag the box/polygon by clicking its mask area. You can exit selecting mode by releasing 'z'.

**Comment by fyu** [comment]
It would be better to show a temp status bar to show the current mode. We can use this https://github.com/fkhadra/react-toastify

**Comment by Scalsol** [comment]
I will take a look. :)

**Comment by siyliepfl** [comment]
The selection mode doesn't work on my side. Do you have an update?

**Review by siyliepfl — CHANGES_REQUESTED** [review]
The function doesn't work on my side.  I couldn't select the mask by clicking on it while pressing z.

**Comment by Scalsol** [comment]
> 
> 
> The function doesn't work on my side. I couldn't select the mask by clicking on it while pressing z.

I will take a look

**Review by siyliepfl — APPROVED** [review]
Works well on myside

**Pull request merged**
